////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 1995-2009 Xilinx, Inc.  All rights reserved.
////////////////////////////////////////////////////////////////////////////////
//   ____  ____ 
//  /   /\/   / 
// /___/  \  /    Vendor: Xilinx 
// \   \   \/     Version : 11.4
//  \   \         Application : xaw2verilog
//  /   /         Filename : analyzer_clock.v
// /___/   /\     Timestamp : 09/07/2014 01:04:53
// \   \  /  \ 
//  \___\/\___\ 
//
//Command: xaw2verilog -st /home/cct/FPGA_Project/PS2_run/ISE/dcm_ip_analyzer/analyzer_clock
//Design Name: analyzer_clock
//Device: xc3s700an-5fgg484
//
// Module analyzer_clock
// Generated by Xilinx Architecture Wizard
// Written for synthesis tool: XST
`timescale 1ns / 1ps

module analyzer_clock(U1_CLKIN_IN, 
                      U1_RST_IN, 
                      U1_CLKIN_IBUFG_OUT, 
                      U1_CLK2X_OUT, 
                      U1_STATUS_OUT, 
                      U2_CLKDV_OUT, 
                      U2_CLK0_OUT, 
                      U2_LOCKED_OUT);

    input U1_CLKIN_IN;
    input U1_RST_IN;
   output U1_CLKIN_IBUFG_OUT;
   output U1_CLK2X_OUT;
   output [7:0] U1_STATUS_OUT;
   output U2_CLKDV_OUT;
   output U2_CLK0_OUT;
   output U2_LOCKED_OUT;
   
   wire GND_BIT;
   wire U1_CLKIN_IBUFG;
   wire U1_CLK2X_BUF;
   wire U1_LOCKED_INV_IN;
   wire U2_CLKDV_BUF;
   wire U2_CLKFB_IN;
   wire U2_CLKIN_IN;
   wire U2_CLK0_BUF;
   wire U2_FDS_Q_OUT;
   wire U2_FD1_Q_OUT;
   wire U2_FD2_Q_OUT;
   wire U2_FD3_Q_OUT;
   wire U2_LOCKED_INV_RST;
   wire U2_OR3_O_OUT;
   wire U2_RST_IN;
   
   assign GND_BIT = 0;
   assign U1_CLKIN_IBUFG_OUT = U1_CLKIN_IBUFG;
   assign U1_CLK2X_OUT = U2_CLKIN_IN;
   assign U2_CLK0_OUT = U2_CLKFB_IN;
   DCM_SP DCM_SP_INST1 (.CLKFB(U2_CLKIN_IN), 
                        .CLKIN(U1_CLKIN_IBUFG), 
                        .DSSEN(GND_BIT), 
                        .PSCLK(GND_BIT), 
                        .PSEN(GND_BIT), 
                        .PSINCDEC(GND_BIT), 
                        .RST(U1_RST_IN), 
                        .CLKDV(), 
                        .CLKFX(), 
                        .CLKFX180(), 
                        .CLK0(), 
                        .CLK2X(U1_CLK2X_BUF), 
                        .CLK2X180(), 
                        .CLK90(), 
                        .CLK180(), 
                        .CLK270(), 
                        .LOCKED(U1_LOCKED_INV_IN), 
                        .PSDONE(), 
                        .STATUS(U1_STATUS_OUT[7:0]));
   defparam DCM_SP_INST1.CLK_FEEDBACK = "2X";
   defparam DCM_SP_INST1.CLKDV_DIVIDE = 10.0;
   defparam DCM_SP_INST1.CLKFX_DIVIDE = 1;
   defparam DCM_SP_INST1.CLKFX_MULTIPLY = 4;
   defparam DCM_SP_INST1.CLKIN_DIVIDE_BY_2 = "FALSE";
   defparam DCM_SP_INST1.CLKIN_PERIOD = 20.000;
   defparam DCM_SP_INST1.CLKOUT_PHASE_SHIFT = "NONE";
   defparam DCM_SP_INST1.DESKEW_ADJUST = "SYSTEM_SYNCHRONOUS";
   defparam DCM_SP_INST1.DFS_FREQUENCY_MODE = "LOW";
   defparam DCM_SP_INST1.DLL_FREQUENCY_MODE = "LOW";
   defparam DCM_SP_INST1.DUTY_CYCLE_CORRECTION = "TRUE";
   defparam DCM_SP_INST1.FACTORY_JF = 16'hC080;
   defparam DCM_SP_INST1.PHASE_SHIFT = 0;
   defparam DCM_SP_INST1.STARTUP_WAIT = "FALSE";
   DCM_SP DCM_SP_INST2 (.CLKFB(U2_CLKFB_IN), 
                        .CLKIN(U2_CLKIN_IN), 
                        .DSSEN(GND_BIT), 
                        .PSCLK(GND_BIT), 
                        .PSEN(GND_BIT), 
                        .PSINCDEC(GND_BIT), 
                        .RST(U2_RST_IN), 
                        .CLKDV(U2_CLKDV_BUF), 
                        .CLKFX(), 
                        .CLKFX180(), 
                        .CLK0(U2_CLK0_BUF), 
                        .CLK2X(), 
                        .CLK2X180(), 
                        .CLK90(), 
                        .CLK180(), 
                        .CLK270(), 
                        .LOCKED(U2_LOCKED_OUT), 
                        .PSDONE(), 
                        .STATUS());
   defparam DCM_SP_INST2.CLK_FEEDBACK = "1X";
   defparam DCM_SP_INST2.CLKDV_DIVIDE = 2.0;
   defparam DCM_SP_INST2.CLKFX_DIVIDE = 1;
   defparam DCM_SP_INST2.CLKFX_MULTIPLY = 4;
   defparam DCM_SP_INST2.CLKIN_DIVIDE_BY_2 = "FALSE";
   defparam DCM_SP_INST2.CLKIN_PERIOD = 10.000;
   defparam DCM_SP_INST2.CLKOUT_PHASE_SHIFT = "NONE";
   defparam DCM_SP_INST2.DESKEW_ADJUST = "SYSTEM_SYNCHRONOUS";
   defparam DCM_SP_INST2.DFS_FREQUENCY_MODE = "LOW";
   defparam DCM_SP_INST2.DLL_FREQUENCY_MODE = "LOW";
   defparam DCM_SP_INST2.DUTY_CYCLE_CORRECTION = "TRUE";
   defparam DCM_SP_INST2.FACTORY_JF = 16'hC080;
   defparam DCM_SP_INST2.PHASE_SHIFT = 0;
   defparam DCM_SP_INST2.STARTUP_WAIT = "FALSE";
   IBUFG U1_CLKIN_IBUFG_INST (.I(U1_CLKIN_IN), 
                              .O(U1_CLKIN_IBUFG));
   BUFG U1_CLK2X_BUFG_INST (.I(U1_CLK2X_BUF), 
                            .O(U2_CLKIN_IN));
   INV U1_INV_INST (.I(U1_LOCKED_INV_IN), 
                    .O(U2_LOCKED_INV_RST));
   BUFG U2_CLKDV_BUFG_INST (.I(U2_CLKDV_BUF), 
                            .O(U2_CLKDV_OUT));
   BUFG U2_CLK0_BUFG_INST (.I(U2_CLK0_BUF), 
                           .O(U2_CLKFB_IN));
   FDS U2_FDS_INST (.C(U2_CLKIN_IN), 
                    .D(GND_BIT), 
                    .S(GND_BIT), 
                    .Q(U2_FDS_Q_OUT));
   FD U2_FD1_INST (.C(U2_CLKIN_IN), 
                   .D(U2_FDS_Q_OUT), 
                   .Q(U2_FD1_Q_OUT));
   FD U2_FD2_INST (.C(U2_CLKIN_IN), 
                   .D(U2_FD1_Q_OUT), 
                   .Q(U2_FD2_Q_OUT));
   FD U2_FD3_INST (.C(U2_CLKIN_IN), 
                   .D(U2_FD2_Q_OUT), 
                   .Q(U2_FD3_Q_OUT));
   OR2 U2_OR2_INST (.I0(U2_LOCKED_INV_RST), 
                    .I1(U2_OR3_O_OUT), 
                    .O(U2_RST_IN));
   OR3 U2_OR3_INST (.I0(U2_FD3_Q_OUT), 
                    .I1(U2_FD2_Q_OUT), 
                    .I2(U2_FD1_Q_OUT), 
                    .O(U2_OR3_O_OUT));
endmodule
